// <auto-generated />
using Ankarunning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Ankarunning.Data.Migrations
{
    [DbContext(typeof(AnkarunningContext))]
    [Migration("20180407212734_routepic")]
    partial class routepic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ankarunning.Data.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Ankarunning.Data.EventPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<byte[]>("Content");

                    b.Property<string>("ContentType");

                    b.Property<long>("EventId");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("EventPhoto");
                });

            modelBuilder.Entity("Ankarunning.Data.Route", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<byte[]>("Content")
                        .IsRequired();

                    b.Property<string>("ContentType")
                        .IsRequired();

                    b.Property<decimal>("Distance");

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<string>("Latitude")
                        .IsRequired();

                    b.Property<string>("Longitude")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<byte[]>("PhotoContent")
                        .IsRequired();

                    b.Property<string>("PhotoContentType")
                        .IsRequired();

                    b.Property<string>("PhotoFileName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("Ankarunning.Data.Training", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("AvgPace")
                        .IsRequired();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<long>("RouteId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("Ankarunning.Data.TrainingPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<byte[]>("Content");

                    b.Property<string>("ContentType");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<long>("TrainingId");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId")
                        .IsUnique();

                    b.ToTable("TrainingPhoto");
                });

            modelBuilder.Entity("Ankarunning.Data.EventPhoto", b =>
                {
                    b.HasOne("Ankarunning.Data.Event", "Event")
                        .WithOne("EventPhoto")
                        .HasForeignKey("Ankarunning.Data.EventPhoto", "EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ankarunning.Data.Training", b =>
                {
                    b.HasOne("Ankarunning.Data.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ankarunning.Data.TrainingPhoto", b =>
                {
                    b.HasOne("Ankarunning.Data.Training", "Training")
                        .WithOne("TrainingPhoto")
                        .HasForeignKey("Ankarunning.Data.TrainingPhoto", "TrainingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
